### ISSUE TITLE
Eagle and Gerbers still at V1

### ISSUE THREAD

**Issue by DirtyEngineer** [tekdemo/tiny-tiny-isp#1]
Just a heads up. The eagle files and gerbers are still of your V1 board.  Do you have the files for the V2 board?  Also, what firmware are you using for the HVSP rest option?

**Comment by tekdemo** [comment]
You're correct! I do have a second board rev, which I'll push here. I don't, however, have any firmware written for it. I got away from the project (and the need for it) before I got anything put together.

**Comment by tekdemo** [comment]
Actually, I'd be careful with the RESET line, since I'm not certain it'll work as anticipated. I have the mosfets reversed, which makes the 12V line go straight over to the programmer uC, and is likely to fry several things. 

In theory, it wouldn't need direct firmware control, as the HVRST line would simply float to 12V when the reset enable line is active. However, it's been quite a while since I've verified the firmware update procedures on AVR chips.

**Comment by DirtyEngineer** [comment]
Thanks for looking in this and for the info about the HVSP. 
Cheers
